---
title: What I'm Doing Now
published-title: Last updated
date: 08/30/2026
---

This is my [now page](https://nownownow.com/about); I can't promise how up-to-date it is, but I try to update it when anything major happens!

## Research Ideas I'm Thinking About

This list is not identical to what I'm currently working on, but it's a good reflection of that plus what I'm working on or thinking about myself or with collaborators.

- Measuring the value of data and model refinements for decision making;
- Probabilistic depth-damage relationships and implications for flood risk assessment;
- Agricultural watershed management and land conservation;
- Compound, multi-hazard, dynamic risk assessments and emergent adaptation risks;
- Open-source and interoperable multi-hazard risk assessment frameworks;
- Integrating political economy into decision analysis framing and modeling; 
- Investing in long-term co-production partnerships;
- Bridging the gap between decision analysis and decision support. 

## Research Logistics
- I am recruiting MS and PhD students for Fall 2027 (Deadline: December, 2026). Please reach out if you are interested in working with me on one of those degrees. 
- I am recruiting a postdoc to work at the intersection of some of the topic areas above with priority for applicants interested in: 

    (1) decision support for local governments to access infrastructure funding and implement flood mitigation measures;
    (2) impact-based flood forecasting;
    (3) probabilistic depth-damage relationships; and
    (4) trade-offs and synergies between flood mitigation and other social objectives for land conservation in agricultural watersheds.

- I am always happy to support those interested in a postdoc with me in securing independent funding if the prospective research seems like a strong mutual fit. 
- I recently converted this webpage over to Quarto and hope to find time soon to set up a lab group webpage and manual.