---
title: "Teaching"
---

## Courses
### University of Iowa 
  * I will teach a course on [Environmental Justice](https://myui.uiowa.edu/my-ui/courses/details.page?ci=174514&id=1060439) in Spring 2026. 
  * I will co-teach a course on [research foundations in Earth, Environment, and Sustainability](https://myui.uiowa.edu/my-ui/courses/details.page?ci=174593&id=1060442) in Spring 2026

### Dartmouth College
* I developed and taught a graduate-level course on [decision analysis for wicked climate problems](https://abpoll.github.io/engs199.20/) in "pilot" mode to four PhD students from different institutions. All materials are open source. Please feel free to adapt this for your teaching needs and reach out with any questions. I plan to add content to this repository with notes on what worked well, what didn't, and how I'd adapt this course for future versions, different audiences, and semester-based systems.  

## Designed and Instructed Modules
### Dartmouth College
* I developed a teaching module on how to produce Findable, Accessible, Interoperable, and Reusable analyses, which I presented in the course Bayesian Statistical Modeling and Computation in the winters of 2024 and 2025. 


## Teaching Assistant
### Boston University
* I was the lab instructor for EE 270, "Data, Models, and Analysis in Earth & Environment", an introductory probability and statistics course for natural and social science applications in environmental sciences, in Spring 2020 and 2021. In 2021, I led the redesign of all computational labs in the course. 

### Stony Brook University
* I was a teaching assistant for CSE 316, "Software Development Fundamentals." In this role, I held 4 open office hours per week where I assisted students on course projects through concept review, implementation advice, and debugging help.